## Data Cleaning

In [179]:
import pandas as pd
import numpy as np

In [180]:
business_data = pd.read_csv("yelp_dataset_csv/yelp_academic_dataset_business.csv")
user_data = pd.read_csv("yelp_dataset_csv/yelp_academic_dataset_user.csv", nrows=50000)

In [181]:
review_data = pd.read_csv("yelp_dataset_csv/yelp_academic_dataset_review.csv", nrows=50000)

In [182]:
business_data.head(20)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,1,"{'BusinessParking': 'None', 'BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-22:0', '..."
6,n_0UpQx1hsNbnPUSlodU8w,Famous Footwear,"8522 Eager Road, Dierbergs Brentwood Point",Brentwood,MO,63144,38.627695,-90.340465,2.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Sporting Goods, Fashion, Shoe Stores, Shopping...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-18:0', ..."
7,qkRM_2X51Yqxk3btlwAQIg,Temple Beth-El,400 Pasadena Ave S,St. Petersburg,FL,33707,27.766590,-82.732983,3.5,5,1,NaN,"Synagogues, Religious Organizations","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ..."
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,MO,63123,38.565165,-90.321087,3.0,19,0,"{'Caters': 'True', 'Alcohol': ""u'full_bar'"", '...","Pubs, Restaurants, Italian, Bars, American (Tr...",NaN
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,10,1,"{'RestaurantsAttire': ""'casual'"", 'Restaurants...","Ice Cream & Frozen Yogurt, Fast Food, Burgers,...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-21:0', '..."
10,UJsufbvfyfONHeWdvAHKjA,Marshalls,21705 Village Lakes Sc Dr,Land O' Lakes,FL,34639,28.190459,-82.457380,3.5,6,1,"{'RestaurantsPriceRange2': '2', 'BikeParking':...","Department Stores, Shopping, Fashion","{'Monday': '9:30-21:30', 'Tuesday': '9:30-21:3..."
11,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,NaN,Tampa Bay,FL,33602,27.955269,-82.456320,4.0,10,1,"{'Alcohol': ""'none'"", 'OutdoorSeating': 'None'...","Vietnamese, Food, Restaurants, Food Trucks","{'Monday': '11:0-14:0', 'Tuesday': '11:0-14:0'..."
12,il_Ro8jwPlHresjw9EGmBg,Denny's,8901 US 31 S,Indianapolis,IN,46227,39.637133,-86.127217,2.5,28,1,"{'RestaurantsReservations': 'False', 'Restaura...","American (Traditional), Restaurants, Diners, B...","{'Monday': '6:0-22:0', 'Tuesday': '6:0-22:0', ..."
13,jaxMSoInw8Poo3XeMJt8lQ,Adams Dental,15 N Missouri Ave,Clearwater,FL,33755,27.966235,-82.787412,5.0,10,1,{'ByAppointmentOnly': 'True'},"General Dentistry, Dentists, Health & Medical,...","{'Monday': '7:30-15:30', 'Tuesday': '7:30-15:3..."
14,0bPLkL0QhhPO5kt1_EXmNQ,Zio's Italian Market,2575 E Bay Dr,Largo,FL,33771,27.916116,-82.760461,4.5,100,0,"{'OutdoorSeating': 'False', 'RestaurantsGoodFo...","Food, Delis, Italian, Bakeries, Restaurants","{'Monday': '10:0-18:0', 'Tuesday': '10:0-20:0'..."
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,1,"{'RestaurantsReservations': 'True', 'Restauran...","Sushi Bars, Restaurants, Japanese","{'Tuesday': '13:30-22:0', 'Wednesday': '13:30-..."
16,rBmpy_Y1UbBx8ggHlyb7hA,Arizona Truck Outfitters,625 N Stone Ave,Tucson,AZ,85705,32.229872,-110.972342,4.5,10,1,"{'DriveThru': 'False', 'BusinessAcceptsCreditC...","Automotive, Auto Parts & Supplies, Auto Custom...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-17:0', '..."
17,M0XSSHqrASOnhgbWDJIpQA,Herb Import Co,712 Adams St,New Orleans,LA,70118,29.941468,-90.129953,4.0,5,1,"{'BusinessParking': ""{'garage': False, 'street...","Vape Shops, Tobacco Shops, Personal Shopping, ...","{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'..."
18,8wGISYjYkE2tSqn3cDMu8A,Nifty Car Rental,1241 Airline Dr,Kenner,LA,70062,29.981183,-90.254012,3.5,14,1,NaN,"Automotive, Car Rental, Hotels & Travel, Truck...","{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ..."
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,1,"{'NoiseLevel': ""u'quiet'"", 'GoodForMeal': ""{'d...","Korean, Restaurants","{'Monday': '11:30-20:30', 'Tuesday': '11:30-20..."

In [183]:
print(business_data.isnull().sum())

business_id         0
name                0
address          5127
city                0
state               0
postal_code        73
latitude            0
longitude           0
stars               0
review_count        0
is_open             0
attributes      13744
categories        103
hours           23223
dtype: int64

In [184]:
print(business_data.isnull().mean() * 100)

business_id      0.000000
name             0.000000
address          3.410134
city             0.000000
state            0.000000
postal_code      0.048555
latitude         0.000000
longitude        0.000000
stars            0.000000
review_count     0.000000
is_open          0.000000
attributes       9.141580
categories       0.068509
hours           15.446370
dtype: float64

In [185]:
business_data = business_data.dropna(subset = ['address', 'postal_code', 'attributes', 'categories'])

In [186]:
print(business_data.isnull().sum())

business_id         0
name                0
address             0
city                0
state               0
postal_code         0
latitude            0
longitude           0
stars               0
review_count        0
is_open             0
attributes          0
categories          0
hours           18209
dtype: int64

### We can drop the null category rows here since the null proportion is so small and categories are really important in our project

In [187]:
business_data['city'].value_counts().head(5)

city
Philadelphia    12943
Tucson           7958
Tampa            7906
Indianapolis     6763
Nashville        6131
Name: count, dtype: int64

In [188]:
philly_data = business_data[
    (business_data['city'] == 'Philadelphia') &
    (business_data['categories'].apply(lambda x: 'Restaurants' in x or 'Food' in x))
].copy()

In [189]:
philly_data.head(30)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,1,"{'RestaurantsReservations': 'True', 'Restauran...","Sushi Bars, Restaurants, Japanese","{'Tuesday': '13:30-22:0', 'Wednesday': '13:30-..."
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,1,"{'NoiseLevel': ""u'quiet'"", 'GoodForMeal': ""{'d...","Korean, Restaurants","{'Monday': '11:30-20:30', 'Tuesday': '11:30-20..."
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,0,"{'Smoking': ""u'no'"", 'NoiseLevel': ""u'average'...","Cocktail Bars, Bars, Italian, Nightlife, Resta...","{'Monday': '16:0-0:0', 'Tuesday': '16:0-0:0', ..."
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,0,"{'RestaurantsReservations': 'False', 'Caters':...","Pizza, Restaurants, Salad, Soup","{'Tuesday': '17:0-21:30', 'Wednesday': '17:0-1..."
35,aPNXGTDkf-4bjhyMBQxqpQ,Craft Hall,901 N Delaware Ave,Philadelphia,PA,19123,39.962582,-75.135657,3.5,65,1,"{'OutdoorSeating': 'True', 'RestaurantsPriceRa...","Eatertainment, Arts & Entertainment, Brewpubs,...","{'Monday': '0:0-0:0', 'Wednesday': '16:0-22:0'..."
76,-4dYswJy7SPcbcERvitmIg,Pathmark,3021 Grays Ferry Ave,Philadelphia,PA,19146,39.940403,-75.193297,2.5,34,0,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Food, Grocery","{'Monday': '6:0-1:0', 'Tuesday': '6:0-1:0', 'W..."
82,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,PA,19104,39.954573,-75.194894,3.0,56,1,"{'Alcohol': ""u'none'"", 'RestaurantsGoodForGrou...","Restaurants, Automotive, Delis, Gas Stations, ...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
130,3BJxm-HnvzdwD1zjmSbmyQ,Golden Chopstick Chinese Restaurant,1800 Spring Garden St,Philadelphia,PA,19130,39.963078,-75.168027,3.0,137,1,"{'GoodForKids': 'True', 'RestaurantsDelivery':...","Restaurants, Chinese","{'Monday': '0:0-0:0', 'Tuesday': '11:0-22:30',..."
151,WYYdQDjx-DsCanlP0DpImQ,J Sushi,243 S 10th St,Philadelphia,PA,19107,39.947033,-75.157434,4.5,72,0,"{'Ambience': ""{'touristy': False, 'hipster': F...","Seafood, Restaurants, Sushi Bars, Japanese","{'Tuesday': '11:0-22:0', 'Wednesday': '11:0-22..."
190,FTFtoylMzkrzqNVSl-bkKw,Giant Food Stores,60 N 23rd St,Philadelphia,PA,19103,39.956528,-75.178014,4.0,19,1,"{'RestaurantsTakeOut': 'True', 'BusinessParkin...","Grocery, Food","{'Monday': '6:0-23:0', 'Tuesday': '6:0-23:0', ..."
199,O1oZpbZNDMH_gz8DhsZCdA,Wendy's,700 E. Hunting Park,Philadelphia,PA,19124,40.012141,-75.115015,1.5,15,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Burgers, Restaurants, Fast Food","{'Monday': '10:0-2:0', 'Tuesday': '10:0-2:0', ..."
205,2dlQX5sP9X6Dlm1MmNOlSw,ReAnimator Coffee,1523 E Susquehanna Ave,Philadelphia,PA,19125,39.976456,-75.127025,4.0,105,1,"{'BusinessParking': ""{'garage': False, 'street...","Food, Coffee & Tea","{'Monday': '0:0-0:0', 'Tuesday': '8:0-15:0', '..."
235,bTve2mwLk5Zc01vRKqc2KQ,Red Hook Coffee & Tea,765 S 4th St,Philadelphia,PA,19147,39.938552,-75.149636,4.5,183,1,"{'BikeParking': 'True', 'OutdoorSeating': 'Tru...","Restaurants, Breakfast & Brunch, Vegan, Bagels...","{'Monday': '7:0-18:0', 'Tuesday': '7:0-18:0', ..."
249,bqmX882_6AxVA_uHEQ70sQ,Shanghai Station,4002 Spruce St,Philadelphia,PA,19104,39.951615,-75.203346,4.0,46,0,"{'Caters': 'False', 'BikeParking': 'False', 'R...","Shanghainese, Restaurants, Sushi Bars, Szechua...",NaN
257,jL_NufxqXi-BpW5uXKsPwQ,CVS Pharmacy,518 Port Royal Ave,Philadelphia,PA,19128,40.061277,-75.237205,3.0,11,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Drugstores, Pharmacy, Health & Medical, Conven...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-22:0', '..."
266,n8ecak12IF_jhnPNs37AZA,Baltic Bakery,2609 Edgemont St,Philadelphia,PA,19125,39.976880,-75.116169,4.5,12,1,"{'RestaurantsDelivery': 'False', 'BusinessAcce...","Food, Bakeries, Restaurants","{'Tuesday': '9:0-17:0', 'Wednesday': '9:0-17:0..."
274,_T0cPZE2ZJOTTlYYKMP64Q,Brown Sugar Bakery & Cafe,219 S 52nd St,Philadelphia,PA,19139,39.956396,-75.225378,4.5,66,1,"{'Caters': 'False', 'Alcohol': ""u'none'"", 'Res...","Cupcakes, Caribbean, Restaurants, Trinidadian,...","{'Monday': '9:0-22:0', 'Tuesday': '9:0-22:0', ..."
276,VbItL6RDULtnw4YvB6EhVg,Jon's Bar & Grille,300 South St,Philadelphia,PA,19147,39.941299,-75.147745,3.0,178,0,"{'Corkage': 'False', 'RestaurantsGoodForGroups...","Tex-Mex, Restaurants, American (Traditional), ...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ..."
312,V-96iACFgPmVjjKACGxd7Q,Fusion Pizza & Grill,"1900 Grant Ave, Ste M-N",Philadelphia,PA,19115,40.083996,-75.035496,2.5,6,0,"{'GoodForKids': 'True', 'RestaurantsGoodForGro...","Ethnic Food, Specialty Food, Restaurants, Food...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'..."
317,0CEUpFtaKhxbmrbSdP9MUQ,Acadia,824 S 8th St,Philadelphia,PA,19147,39.938948,-75.156408,4.0,79,0,"{'Caters': 'True', 'DogsAllowed': 'True', 'Res...","Restaurants, Cajun/Creole, Southern, Nightlife...","{'Monday': '0:0-0:0', 'Tuesday': '17:0-23:0', ..."
365,GVqXNt0HKJLpciN9ePxnWw,Crown Fried Chicken,1128 S Broad St,Philadelphia,PA,19146,39.936891,-75.167284,2.5,16,1,"{'OutdoorSeating': 'False', 'Alcohol': ""u'none...","Restaurants, Fast Food",NaN
372,dChRGpit9fM_kZK5pafNyA,The Love,130 S 18th St,Philadelphia,PA,19103,39.950656,-75.170899,4.0,618,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Restaurants, American (New), Breakfast & Brunc...","{'Monday': '0:0-0:0', 'Tuesday': '17:0-21:0', ..."
389,cDekcTE1qwpz8ROlYixhqg,Philly Homebrew Outlet East,1447 N American St,Philadelphia,PA,19122,39.973681,-75.139648,5.0,32,0,"{'RestaurantsPriceRange2': '2', 'GoodForKids':...","Shopping, Food, Arts & Entertainment, Wholesal...","{'Monday': '11:0-19:0', 'Tuesday': '11:0-19:0'..."
409,QWqKTWQ2OiDgo3dzNkpung,Jong Ka Jib,6600 N 5th St,Philadelphia,PA,19126,40.052064,-75.127394,4.5,351,1,"{'Alcohol': ""u'none'"", 'RestaurantsGoodForGrou...","Korean, Restaurants","{'Monday': '10:30-22:30', 'Tuesday': '10:30-22..."
436,i_cFU5_dQexbjJA9rmf_WA,Marcie Blaine,108 S 13th St,Philadelphia,PA,19107,39.950036,-75.162158,3.5,8,1,"{'BusinessParking': ""{'garage': False, 'street...","Desserts, Specialty Food, Food, Chocolatiers &...",NaN
443,7mpYTDb24SywNMRn3yeakQ,The Twisted Tail,509 S 2nd St,Philadelphia,PA,19147,39.941877,-75.145199,4.0,604,1,"{'BusinessParking': ""{'garage': False, 'street...","Event Planning & Services, Whiskey Bars, Ameri...","{'Monday': '0:0-0:0', 'Tuesday': '16:0-22:0', ..."
472,5iuo1kvv0XZMS0bUOoLz2Q,Bistro St. Tropez,"2400 Market St, Ste 427",Philadelphia,PA,19103,39.953592,-75.179423,3.5,163,0,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Restaurants, French","{'Monday': '11:30-15:0', 'Tuesday': '11:30-15:..."
502,bchZXVE4feVx4Q5rhIRCGg,NY Bagel Cafe & Deli,"4514 B City Line Ave, Ste 220",Philadelphia,PA,19131,40.002783,-75.222270,3.0,52,0,"{'RestaurantsReservations': 'True', 'GoodForKi...","Restaurants, Food, Bagels, Breakfast & Brunch,...","{'Monday': '0:0-0:0', 'Tuesday': '7:0-16:0', '..."
523,ngvE1G9IckUO-ljZBFo23w,Mumbai Bistro,930 Locust St,Philadelphia,PA,19107,39.947207,-75.157252,4.0,217,0,"{'RestaurantsReservations': 'False', 'OutdoorS...","Indian, Restaurants","{'Tuesday': '11:30-21:0', 'Wednesday': '11:30-..."

In [190]:
print(philly_data.isnull().mean() * 100)
len(philly_data)

business_id      0.000000
name             0.000000
address          0.000000
city             0.000000
state            0.000000
postal_code      0.000000
latitude         0.000000
longitude        0.000000
stars            0.000000
review_count     0.000000
is_open          0.000000
attributes       0.000000
categories       0.000000
hours           17.106211
dtype: float64

6939

In [191]:
import ast
philly_data['hours'] = philly_data['hours'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [192]:
def extract_hours_features(hours_dict):
    if not isinstance(hours_dict, dict) or len(hours_dict) == 0:
        return pd.Series([0, 0, 0])

    is_open_morning = 0
    is_open_latenight = 0
    open_on_weekends = 0

    for day, hours in hours_dict.items():
        try:
            open_time, close_time = hours.split('-')

            # Convert to hour integers
            open_hour = int(open_time.split(':')[0])
            close_hour = int(close_time.split(':')[0])

            # Morning check
            if open_hour < 10:
                is_open_morning = 1

            # Late night check
            if close_hour >= 22:
                is_open_latenight = 1

            # Weekend check
            if day in ['Saturday', 'Sunday']:
                open_on_weekends = 1

        except:
            continue

    return pd.Series([is_open_morning, is_open_latenight, open_on_weekends])

In [193]:
philly_data[['time_is_open_morning', 'time_is_open_latenight', 'time_open_on_weekends']] = philly_data['hours'].apply(extract_hours_features)

In [194]:
philly_data[['time_is_open_morning', 'time_is_open_latenight', 'time_open_on_weekends']] = philly_data[['time_is_open_morning', 'time_is_open_latenight', 'time_open_on_weekends']].fillna(0).astype(int)

In [195]:
philly_data.head(20)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,time_is_open_morning,time_is_open_latenight,time_open_on_weekends
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...",1,0,1
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,1,"{'RestaurantsReservations': 'True', 'Restauran...","Sushi Bars, Restaurants, Japanese","{'Tuesday': '13:30-22:0', 'Wednesday': '13:30-...",0,1,1
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,1,"{'NoiseLevel': ""u'quiet'"", 'GoodForMeal': ""{'d...","Korean, Restaurants","{'Monday': '11:30-20:30', 'Tuesday': '11:30-20...",0,0,1
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,0,"{'Smoking': ""u'no'"", 'NoiseLevel': ""u'average'...","Cocktail Bars, Bars, Italian, Nightlife, Resta...","{'Monday': '16:0-0:0', 'Tuesday': '16:0-0:0', ...",0,0,1
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,0,"{'RestaurantsReservations': 'False', 'Caters':...","Pizza, Restaurants, Salad, Soup","{'Tuesday': '17:0-21:30', 'Wednesday': '17:0-1...",0,0,1
35,aPNXGTDkf-4bjhyMBQxqpQ,Craft Hall,901 N Delaware Ave,Philadelphia,PA,19123,39.962582,-75.135657,3.5,65,1,"{'OutdoorSeating': 'True', 'RestaurantsPriceRa...","Eatertainment, Arts & Entertainment, Brewpubs,...","{'Monday': '0:0-0:0', 'Wednesday': '16:0-22:0'...",1,1,1
76,-4dYswJy7SPcbcERvitmIg,Pathmark,3021 Grays Ferry Ave,Philadelphia,PA,19146,39.940403,-75.193297,2.5,34,0,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Food, Grocery","{'Monday': '6:0-1:0', 'Tuesday': '6:0-1:0', 'W...",1,0,1
82,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,PA,19104,39.954573,-75.194894,3.0,56,1,"{'Alcohol': ""u'none'"", 'RestaurantsGoodForGrou...","Restaurants, Automotive, Delis, Gas Stations, ...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",1,0,1
130,3BJxm-HnvzdwD1zjmSbmyQ,Golden Chopstick Chinese Restaurant,1800 Spring Garden St,Philadelphia,PA,19130,39.963078,-75.168027,3.0,137,1,"{'GoodForKids': 'True', 'RestaurantsDelivery':...","Restaurants, Chinese","{'Monday': '0:0-0:0', 'Tuesday': '11:0-22:30',...",1,1,1
151,WYYdQDjx-DsCanlP0DpImQ,J Sushi,243 S 10th St,Philadelphia,PA,19107,39.947033,-75.157434,4.5,72,0,"{'Ambience': ""{'touristy': False, 'hipster': F...","Seafood, Restaurants, Sushi Bars, Japanese","{'Tuesday': '11:0-22:0', 'Wednesday': '11:0-22...",0,1,1
190,FTFtoylMzkrzqNVSl-bkKw,Giant Food Stores,60 N 23rd St,Philadelphia,PA,19103,39.956528,-75.178014,4.0,19,1,"{'RestaurantsTakeOut': 'True', 'BusinessParkin...","Grocery, Food","{'Monday': '6:0-23:0', 'Tuesday': '6:0-23:0', ...",1,1,1
199,O1oZpbZNDMH_gz8DhsZCdA,Wendy's,700 E. Hunting Park,Philadelphia,PA,19124,40.012141,-75.115015,1.5,15,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Burgers, Restaurants, Fast Food","{'Monday': '10:0-2:0', 'Tuesday': '10:0-2:0', ...",0,0,1
205,2dlQX5sP9X6Dlm1MmNOlSw,ReAnimator Coffee,1523 E Susquehanna Ave,Philadelphia,PA,19125,39.976456,-75.127025,4.0,105,1,"{'BusinessParking': ""{'garage': False, 'street...","Food, Coffee & Tea","{'Monday': '0:0-0:0', 'Tuesday': '8:0-15:0', '...",1,0,1
235,bTve2mwLk5Zc01vRKqc2KQ,Red Hook Coffee & Tea,765 S 4th St,Philadelphia,PA,19147,39.938552,-75.149636,4.5,183,1,"{'BikeParking': 'True', 'OutdoorSeating': 'Tru...","Restaurants, Breakfast & Brunch, Vegan, Bagels...","{'Monday': '7:0-18:0', 'Tuesday': '7:0-18:0', ...",1,0,1
249,bqmX882_6AxVA_uHEQ70sQ,Shanghai Station,4002 Spruce St,Philadelphia,PA,19104,39.951615,-75.203346,4.0,46,0,"{'Caters': 'False', 'BikeParking': 'False', 'R...","Shanghainese, Restaurants, Sushi Bars, Szechua...",NaN,0,0,0
257,jL_NufxqXi-BpW5uXKsPwQ,CVS Pharmacy,518 Port Royal Ave,Philadelphia,PA,19128,40.061277,-75.237205,3.0,11,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Drugstores, Pharmacy, Health & Medical, Conven...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-22:0', '...",1,1,1
266,n8ecak12IF_jhnPNs37AZA,Baltic Bakery,2609 Edgemont St,Philadelphia,PA,19125,39.976880,-75.116169,4.5,12,1,"{'RestaurantsDelivery': 'False', 'BusinessAcce...","Food, Bakeries, Restaurants","{'Tuesday': '9:0-17:0', 'Wednesday': '9:0-17:0...",1,0,1
274,_T0cPZE2ZJOTTlYYKMP64Q,Brown Sugar Bakery & Cafe,219 S 52nd St,Philadelphia,PA,19139,39.956396,-75.225378,4.5,66,1,"{'Caters': 'False', 'Alcohol': ""u'none'"", 'Res...","Cupcakes, Caribbean, Restaurants, Trinidadian,...","{'Monday': '9:0-22:0', 'Tuesday': '9:0-22:0', ...",1,1,1
276,VbItL6RDULtnw4YvB6EhVg,Jon's Bar & Grille,300 South St,Philadelphia,PA,19147,39.941299,-75.147745,3.0,178,0,"{'Corkage': 'False', 'RestaurantsGoodForGroups...","Tex-Mex, Restaurants, American (Traditional), ...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ...",0,0,1
312,V-96iACFgPmVjjKACGxd7Q,Fusion Pizza & Grill,"1900 Grant Ave, Ste M-N",Philadelphia,PA,19115,40.083996,-75.035496,2.5,6,0,"{'GoodForKids': 'True', 'RestaurantsGoodForGro...","Ethnic Food, Specialty Food, Restaurants, Food...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",0,1,1

In [196]:
from sklearn.preprocessing import MultiLabelBinarizer

# Make a safe copy
philly_data = philly_data.copy()

# Convert comma-separated strings into lists
philly_data['categories'] = philly_data['categories'].apply(
    lambda x: [item.strip() for item in x.split(',')] if isinstance(x, str) else []
)

# One-hot encode
mlb = MultiLabelBinarizer()

categories_df = pd.DataFrame(
    mlb.fit_transform(philly_data['categories']),
    columns=mlb.classes_,
    index=philly_data.index
)

# ✅ Add prefix "cat_" to all category columns
categories_df.columns = ['cat_' + col.lower().replace(' ', '_') for col in categories_df.columns]

# Merge back
philly_data = pd.concat([philly_data, categories_df], axis=1)

In [197]:
philly_data.columns

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count',
       ...
       'cat_wholesale_stores', 'cat_wholesalers', 'cat_wine_&_spirits',
       'cat_wine_bars', 'cat_wine_tasting_classes', 'cat_wine_tasting_room',
       'cat_wineries', 'cat_women's_clothing', 'cat_wraps', 'cat_yoga'],
      dtype='object', length=473)

In [198]:
print(len(mlb.classes_))
print(mlb.classes_)

456
['Acai Bowls' 'Accessories' 'Active Life' 'Acupuncture' 'Adult'
 'Adult Education' 'Adult Entertainment' 'Afghan' 'African'
 'Airport Shuttles' 'American (New)' 'American (Traditional)' 'Antiques'
 'Apartments' 'Appliances' 'Arabic' 'Arcades' 'Argentine' 'Armenian'
 'Art Classes' 'Art Galleries' 'Art Museums' 'Art Supplies'
 'Arts & Crafts' 'Arts & Entertainment' 'Asian Fusion' 'Australian'
 'Austrian' 'Automotive' 'Axe Throwing' 'Bagels' 'Bakeries' 'Bangladeshi'
 'Banks & Credit Unions' 'Bar Crawl' 'Barbeque' 'Barbers' 'Barre Classes'
 'Bars' 'Bartenders' 'Basque' 'Beaches' 'Beauty & Spas' 'Beer' 'Beer Bar'
 'Beer Gardens' 'Beer Hall' 'Beer Tours' 'Belgian' 'Beverage Store'
 'Bike Rentals' 'Bike Repair/Maintenance' 'Bikes' 'Bistros'
 'Boat Charters' 'Boat Tours' 'Boating' 'Body Contouring' 'Books'
 'Bookstores' 'Bowling' 'Brasseries' 'Brazilian' 'Breakfast & Brunch'
 'Breweries' 'Brewing Supplies' 'Brewpubs' 'British' 'Bubble Tea'
 'Buddhist Temples' 'Buffets' 'Burgers' 'Burmese' 'Butcher' 'CSA' 'Cafes'
 'Cafeteria' 'Cajun/Creole' 'Cambodian' 'Candle Stores' 'Candy Stores'
 'Cannabis Clinics' 'Cannabis Dispensaries' 'Cantonese' 'Car Rental'
 'Cardio Classes' 'Cards & Stationery' 'Caribbean' 'Casinos' 'Caterers'
 'Champagne Bars' 'Cheese Shops' 'Cheesesteaks' 'Chicken Shop'
 'Chicken Wings' 'Chinese' 'Chiropractors' 'Chocolatiers & Shops'
 'Christmas Trees' 'Cideries' 'Cinema' 'Cocktail Bars' 'Coffee & Tea'
 'Coffee Roasteries' 'Colleges & Universities' 'Colombian' 'Comedy Clubs'
 'Comfort Food' 'Comic Books' 'Community Service/Non-Profit'
 'Convenience Stores' 'Conveyor Belt Sushi' 'Cooking Classes'
 'Cooking Schools' 'Cosmetics & Beauty Supply' 'Costumes' 'Creperies'
 'Cuban' 'Cupcakes' 'Custom Cakes' 'Customized Merchandise' 'Dance Clubs'
 'Day Spas' 'Delicatessen' 'Delis' 'Dentists' 'Department Stores'
 'Dermatologists' 'Desserts' 'Dim Sum' 'Diners' 'Dinner Theater'
 'Discount Store' 'Distilleries' 'Dive Bars' 'Do-It-Yourself Food'
 'Doctors' 'Dominican' 'Donuts' 'Drugstores' 'Dry Cleaning & Laundry'
 'Eatertainment' 'Education' 'Egyptian' 'Electronics' 'Emergency Rooms'
 'Empanadas' 'Escape Games' 'Ethiopian' 'Ethnic Food' 'Ethnic Grocery'
 'Event Planning & Services' 'Eyewear & Opticians' 'Falafel'
 'Farmers Market' 'Fashion' 'Fast Food' 'Festivals' 'Filipino'
 'Financial Advising' 'Financial Services' 'Fish & Chips' 'Fishing'
 'Fitness & Instruction' 'Floral Designers' 'Florists' 'Flowers & Gifts'
 'Fondue' 'Food' 'Food Banks' 'Food Court' 'Food Delivery Services'
 'Food Stands' 'Food Tours' 'Food Trucks' 'French' 'Fruits & Veggies'
 'Furniture Reupholstery' 'Furniture Stores' 'Fuzhou' 'Gardeners'
 'Gas Stations' 'Gastropubs' 'Gay Bars' 'Gelato' 'General Dentistry'
 'Georgian' 'German' 'Gift Shops' 'Gluten-Free' 'Golf' 'Golf Lessons'
 'Greek' 'Grocery' 'Gyms' 'Hainan' 'Hair Salons' 'Haitian' 'Halal'
 'Hawaiian' 'Head Shops' 'Health & Medical' 'Health Markets'
 'Herbal Shops' 'Herbs & Spices' 'Himalayan/Nepalese' 'Hobby Shops'
 'Home & Garden' 'Home Decor' 'Home Health Care' 'Home Services'
 'Honduran' 'Honey' 'Hong Kong Style Cafe' 'Hookah Bars' 'Hospitals'
 'Hot Dogs' 'Hot Pot' 'Hotel bar' 'Hotels' 'Hotels & Travel' 'Hungarian'
 'Hunting & Fishing Supplies' 'IT Services & Computer Repair' 'Iberian'
 'Ice Cream & Frozen Yogurt' 'Imported Food' 'Indian' 'Indonesian'
 'Indoor Playcentre' 'International Grocery' 'Internet Cafes' 'Irish'
 'Irish Pub' 'Israeli' 'Italian' 'Izakaya' 'Japanese' 'Japanese Curry'
 'Jazz & Blues' 'Jewelry' 'Juice Bars & Smoothies' 'Karaoke' 'Kebab'
 'Kids Activities' 'Kitchen & Bath' 'Kitchen Supplies' 'Knitting Supplies'
 'Kombucha' 'Korean' 'Kosher' 'LAN Centers'
 'Landmarks & Historical Buildings' 'Laotian' 'Latin American'
 'Laundromat' 'Laundry Services' 'Lebanese' 'Life Coach' 'Live/Raw Food'
 'Local Flavor' 'Local Services' 'Lounges' 'Macarons' 'Mags' 'Malaysian'
 'Marketing' 'Mass Media' 'Massage' 'Massage Therapy' 'Meat Shops'
 'Medical Centers' 'Medical Spas' 'Medical Supplies' 'Mediterranean'
 "Men's Clothing" 'Mexican' 'Middle Eastern' 'Mini Golf'
 'Mobile Phone Repair' 'Mobile Phones' 'Modern European' 'Mongolian'
 'Moroccan' 'Mountain Biking' 'Museums' 'Music & DVDs' 'Music & Video'
 'Music Venues' 'Nail Salons' 'Nail Technicians' 'Naturopathic/Holistic'
 'New Mexican Cuisine' 'Newspapers & Magazines' 'Nightlife' 'Noodles'
 'Nurseries & Gardening' 'Nutritionists' 'Olive Oil' 'Organic Stores'
 'Outdoor Gear' 'Paint & Sip' 'Pakistani' 'Pan Asian' 'Parks'
 'Party & Event Planning' 'Party Supplies' 'Pasta Shops'
 'Patisserie/Cake Shop' 'Performing Arts' 'Persian/Iranian'
 'Personal Chefs' 'Peruvian' 'Pest Control' 'Pet Adoption' 'Pets'
 'Pharmacy' 'Photography Stores & Services' 'Piano Bars' 'Pilates' 'Pizza'
 'Playgrounds' 'Plumbing' 'Poke' 'Polish' 'Pool Halls'
 'Pop-Up Restaurants' 'Pop-up Shops' 'Popcorn Shops' 'Portuguese'
 'Poutineries' 'Pretzels' 'Print Media' 'Printing Services'
 'Professional Services' 'Propane' 'Property Management' 'Public Art'
 'Public Markets' 'Public Services & Government' 'Public Transportation'
 'Pubs' 'Puerto Rican' 'Ramen' 'Real Estate' 'Real Estate Agents'
 'Recreation Centers' 'Recycling Center' 'Reflexology'
 'Religious Organizations' 'Restaurant Supplies' 'Restaurants' 'Russian'
 'Salad' 'Salvadoran' 'Sandwiches' 'Sardinian' 'Saunas' 'Scandinavian'
 'Seafood' 'Seafood Markets' 'Senegalese' 'Shanghainese' 'Shaved Ice'
 'Shipping Centers' 'Shopping' 'Shopping Centers' 'Sicilian' 'Singaporean'
 'Skating Rinks' 'Skin Care' 'Smokehouse' 'Social Clubs' 'Soul Food'
 'Soup' 'South African' 'Southern' 'Souvenir Shops' 'Spanish'
 'Speakeasies' 'Special Education' 'Specialty Food' 'Specialty Schools'
 'Sporting Goods' 'Sports Bars' 'Sports Betting' 'Sports Clubs'
 'Sports Wear' 'Steakhouses' 'Street Vendors' 'Strip Clubs' 'Supper Clubs'
 'Sushi Bars' 'Swimming Pools' 'Szechuan' 'Tabletop Games' 'Tacos'
 'Taiwanese' 'Tapas Bars' 'Tapas/Small Plates' 'Tasting Classes' 'Tattoo'
 'Taxis' 'Tea Rooms' 'Team Building Activities' 'Tennis' 'Teppanyaki'
 'Tex-Mex' 'Thai' 'Themed Cafes' 'Ticket Sales' 'Tiki Bars' 'Tires'
 'Tobacco Shops' 'Tours' 'Toy Stores' 'Traditional Chinese Medicine'
 'Train Stations' 'Transportation' 'Travel Services' 'Trinidadian'
 'Turkish' 'Ukrainian' 'Unofficial Yelp Events' 'Urgent Care' 'Urologists'
 'Used' 'Used Bookstore' 'Uzbek' 'Vape Shops' 'Vegan' 'Vegetarian'
 'Venezuelan' 'Venues & Event Spaces' 'Videos & Video Game Rental'
 'Vietnamese' 'Vintage & Consignment' 'Vinyl Records' 'Visitor Centers'
 'Vitamins & Supplements' 'Waffles' 'Walking Tours' 'Watches'
 'Wedding Planning' 'Weight Loss Centers' 'Whiskey Bars'
 'Wholesale Stores' 'Wholesalers' 'Wine & Spirits' 'Wine Bars'
 'Wine Tasting Classes' 'Wine Tasting Room' 'Wineries' "Women's Clothing"
 'Wraps' 'Yoga']

In [199]:
philly_data.head(20)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,cat_wholesale_stores,cat_wholesalers,cat_wine_&_spirits,cat_wine_bars,cat_wine_tasting_classes,cat_wine_tasting_room,cat_wineries,cat_women's_clothing,cat_wraps,cat_yoga
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,0,0,0,0,0,0,0,0,0,0
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,...,0,0,0,0,0,0,0,0,0,0
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,...,0,0,0,0,0,0,0,0,0,0
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,...,0,0,0,0,0,0,0,0,0,0
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,...,0,0,0,0,0,0,0,0,0,0
35,aPNXGTDkf-4bjhyMBQxqpQ,Craft Hall,901 N Delaware Ave,Philadelphia,PA,19123,39.962582,-75.135657,3.5,65,...,0,0,0,0,0,0,0,0,0,0
76,-4dYswJy7SPcbcERvitmIg,Pathmark,3021 Grays Ferry Ave,Philadelphia,PA,19146,39.940403,-75.193297,2.5,34,...,0,0,0,0,0,0,0,0,0,0
82,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,PA,19104,39.954573,-75.194894,3.0,56,...,0,0,0,0,0,0,0,0,0,0
130,3BJxm-HnvzdwD1zjmSbmyQ,Golden Chopstick Chinese Restaurant,1800 Spring Garden St,Philadelphia,PA,19130,39.963078,-75.168027,3.0,137,...,0,0,0,0,0,0,0,0,0,0
151,WYYdQDjx-DsCanlP0DpImQ,J Sushi,243 S 10th St,Philadelphia,PA,19107,39.947033,-75.157434,4.5,72,...,0,0,0,0,0,0,0,0,0,0
190,FTFtoylMzkrzqNVSl-bkKw,Giant Food Stores,60 N 23rd St,Philadelphia,PA,19103,39.956528,-75.178014,4.0,19,...,0,0,0,0,0,0,0,0,0,0
199,O1oZpbZNDMH_gz8DhsZCdA,Wendy's,700 E. Hunting Park,Philadelphia,PA,19124,40.012141,-75.115015,1.5,15,...,0,0,0,0,0,0,0,0,0,0
205,2dlQX5sP9X6Dlm1MmNOlSw,ReAnimator Coffee,1523 E Susquehanna Ave,Philadelphia,PA,19125,39.976456,-75.127025,4.0,105,...,0,0,0,0,0,0,0,0,0,0
235,bTve2mwLk5Zc01vRKqc2KQ,Red Hook Coffee & Tea,765 S 4th St,Philadelphia,PA,19147,39.938552,-75.149636,4.5,183,...,0,0,0,0,0,0,0,0,0,0
249,bqmX882_6AxVA_uHEQ70sQ,Shanghai Station,4002 Spruce St,Philadelphia,PA,19104,39.951615,-75.203346,4.0,46,...,0,0,0,0,0,0,0,0,0,0
257,jL_NufxqXi-BpW5uXKsPwQ,CVS Pharmacy,518 Port Royal Ave,Philadelphia,PA,19128,40.061277,-75.237205,3.0,11,...,0,0,0,0,0,0,0,0,0,0
266,n8ecak12IF_jhnPNs37AZA,Baltic Bakery,2609 Edgemont St,Philadelphia,PA,19125,39.976880,-75.116169,4.5,12,...,0,0,0,0,0,0,0,0,0,0
274,_T0cPZE2ZJOTTlYYKMP64Q,Brown Sugar Bakery & Cafe,219 S 52nd St,Philadelphia,PA,19139,39.956396,-75.225378,4.5,66,...,0,0,0,0,0,0,0,0,0,0
276,VbItL6RDULtnw4YvB6EhVg,Jon's Bar & Grille,300 South St,Philadelphia,PA,19147,39.941299,-75.147745,3.0,178,...,0,0,0,0,0,0,0,0,0,0
312,V-96iACFgPmVjjKACGxd7Q,Fusion Pizza & Grill,"1900 Grant Ave, Ste M-N",Philadelphia,PA,19115,40.083996,-75.035496,2.5,6,...,0,0,0,0,0,0,0,0,0,0

In [200]:
import re

# Make safe copy
philly_data = philly_data.copy()

# -----------------------------
# Step 1: Parse attributes column into dict
# -----------------------------
def safe_parse(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except:
            return {}
    return {}

philly_data['attributes'] = philly_data['attributes'].apply(safe_parse)

# -----------------------------
# Step 2: Flatten + clean values
# -----------------------------
def clean_value(val):
    if isinstance(val, str):
        val = val.strip()

        # Handle nested dict stored as string
        if val.startswith('{') and val.endswith('}'):
            try:
                return ast.literal_eval(val)
            except:
                return {}

        # Normalize unicode-like strings: u'free'
        val = val.replace("u'", "").replace("'", "")

        # Boolean conversion
        if val.lower() == 'true':
            return 1
        if val.lower() == 'false':
            return 0

        # Numeric conversion
        if val.isdigit():
            return int(val)

        return val

    return val


def flatten_attributes(attr_dict):
    result = {}

    if not isinstance(attr_dict, dict):
        return result

    for key, val in attr_dict.items():
        val = clean_value(val)

        # If nested dictionary → flatten
        if isinstance(val, dict):
            for sub_key, sub_val in val.items():
                sub_val = clean_value(sub_val)

                col_name = f"attr_{key}_{sub_key}"
                result[col_name] = 1 if sub_val in [True, 1] else 0

        else:
            col_name = f"attr_{key}"

            # Boolean-like
            if val in [True, 1]:
                result[col_name] = 1
            elif val in [False, 0]:
                result[col_name] = 0
            else:
                result[col_name] = val

    return result

# Apply flattening
attr_df = philly_data['attributes'].apply(flatten_attributes).apply(pd.Series)

# -----------------------------
# Step 3: Clean column names
# -----------------------------
attr_df.columns = [
    re.sub(r'[^a-z0-9]+', '_', col.lower()).strip('_')
    for col in attr_df.columns
]

# -----------------------------
# Step 4: Fill missing values
# -----------------------------
attr_df = attr_df.fillna(0)

# -----------------------------
# Step 5: Merge back
# -----------------------------
philly_data = pd.concat([philly_data, attr_df], axis=1)

# Optional: drop original column
# philly_data = philly_data.drop(columns=['attributes'])

In [201]:
print(philly_data.head(20))

                business_id                                 name  \
3    MTSW4McQd7CbVtyjqoe9mw                   St Honore Pastries
15   MUTTqe8uqyMdBl186RmNeA                             Tuna Bar
19   ROeacJQwBeh05Rqg7F6TCg                                  BAP
28   QdN72BWoyFypdGJhhI5r7g                              Bar One
31   Mjboz24M9NlBeiOJKLEd_Q                     DeSandro on Main
35   aPNXGTDkf-4bjhyMBQxqpQ                           Craft Hall
76   -4dYswJy7SPcbcERvitmIg                             Pathmark
82   ppFCk9aQkM338Rgwpl2F5A                                 Wawa
130  3BJxm-HnvzdwD1zjmSbmyQ  Golden Chopstick Chinese Restaurant
151  WYYdQDjx-DsCanlP0DpImQ                              J Sushi
190  FTFtoylMzkrzqNVSl-bkKw                    Giant Food Stores
199  O1oZpbZNDMH_gz8DhsZCdA                              Wendy's
205  2dlQX5sP9X6Dlm1MmNOlSw                    ReAnimator Coffee
235  bTve2mwLk5Zc01vRKqc2KQ                Red Hook Coffee & Tea
249  bqmX882_6AxVA_uHEQ70sQ                     Shanghai Station
257  jL_NufxqXi-BpW5uXKsPwQ                         CVS Pharmacy
266  n8ecak12IF_jhnPNs37AZA                        Baltic Bakery
274  _T0cPZE2ZJOTTlYYKMP64Q            Brown Sugar Bakery & Cafe
276  VbItL6RDULtnw4YvB6EhVg                   Jon's Bar & Grille
312  V-96iACFgPmVjjKACGxd7Q                 Fusion Pizza & Grill

                     address          city state postal_code   latitude  \
3                935 Race St  Philadelphia    PA       19107  39.955505
15               205 Race St  Philadelphia    PA       19106  39.953949
19             1224 South St  Philadelphia    PA       19147  39.943223
28              767 S 9th St  Philadelphia    PA       19147  39.939825
31              4105 Main St  Philadelphia    PA       19127  40.022466
35        901 N Delaware Ave  Philadelphia    PA       19123  39.962582
76      3021 Grays Ferry Ave  Philadelphia    PA       19146  39.940403
82          3604 Chestnut St  Philadelphia    PA       19104  39.954573
130    1800 Spring Garden St  Philadelphia    PA       19130  39.963078
151            243 S 10th St  Philadelphia    PA       19107  39.947033
190             60 N 23rd St  Philadelphia    PA       19103  39.956528
199      700 E. Hunting Park  Philadelphia    PA       19124  40.012141
205   1523 E Susquehanna Ave  Philadelphia    PA       19125  39.976456
235             765 S 4th St  Philadelphia    PA       19147  39.938552
249           4002 Spruce St  Philadelphia    PA       19104  39.951615
257       518 Port Royal Ave  Philadelphia    PA       19128  40.061277
266         2609 Edgemont St  Philadelphia    PA       19125  39.976880
274            219 S 52nd St  Philadelphia    PA       19139  39.956396
276             300 South St  Philadelphia    PA       19147  39.941299
312  1900 Grant Ave, Ste M-N  Philadelphia    PA       19115  40.083996

     longitude  stars  review_count  ...  attr_music attr_bestnights  \
3   -75.155564    4.0            80  ...           0               0
15  -75.143226    4.0           245  ...           0               0
19  -75.162568    4.5           205  ...           0               0
28  -75.157447    4.0            65  ...           0               0
31  -75.218314    3.0            41  ...           0               0
35  -75.135657    3.5            65  ...           0               0
76  -75.193297    2.5            34  ...           0               0
82  -75.194894    3.0            56  ...           0               0
130 -75.168027    3.0           137  ...           0               0
151 -75.157434    4.5            72  ...           0               0
190 -75.178014    4.0            19  ...           0               0
199 -75.115015    1.5            15  ...           0               0
205 -75.127025    4.0           105  ...           0               0
235 -75.149636    4.5           183  ...           0               0
249 -75.203346    4.0            46  ...           0               0
257 -75.237205    3.0            11  ...           0               0
266 -75.116169    4.5            12  ...           0               0
274 -75.225378    4.5            66  ...           0               0
276 -75.147745    3.0           178  ...           0               0
312 -75.035496    2.5             6  ...           0               0

    attr_dietaryrestrictions_dairy_free attr_dietaryrestrictions_gluten_free  \
3                                   0.0                                  0.0
15                                  0.0                                  0.0
19                                  0.0                                  0.0
28                                  0.0                                  0.0
31                                  0.0                                  0.0
35                                  0.0                                  0.0
76                                  0.0                                  0.0
82                                  0.0                                  0.0
130                                 0.0                                  0.0
151                                 0.0                                  0.0
190                                 0.0                                  0.0
199                                 0.0                                  0.0
205                                 0.0                                  0.0
235                                 0.0                                  0.0
249                                 0.0                                  0.0
257                                 0.0                                  0.0
266                                 0.0                                  0.0
274                                 0.0                                  0.0
276                                 0.0                                  0.0
312                                 0.0                                  0.0

     attr_dietaryrestrictions_vegan  attr_dietaryrestrictions_kosher  \
3                               0.0                              0.0
15                              0.0                              0.0
19                              0.0                              0.0
28                              0.0                              0.0
31                              0.0                              0.0
35                              0.0                              0.0
76                              0.0                              0.0
82                              0.0                              0.0
130                             0.0                              0.0
151                             0.0                              0.0
190                             0.0                              0.0
199                             0.0                              0.0
205                             0.0                              0.0
235                             0.0                              0.0
249                             0.0                              0.0
257                             0.0                              0.0
266                             0.0                              0.0
274                             0.0                              0.0
276                             0.0                              0.0
312                             0.0                              0.0

     attr_dietaryrestrictions_halal  attr_dietaryrestrictions_soy_free  \
3                               0.0                                0.0
15                              0.0                                0.0
19                              0.0                                0.0
28                              0.0                                0.0
31                              0.0                                0.0
35                              0.0                                0.0
76                              0.0                                0.0
82                              0.0                                0.0
130                             0.0                                0.0
151                             0.0                                0.0
190                             0.0                                0.0
199                             0.0                                0.0
205                             0.0                                0.0
235                             0.0                                0.0
249                             0.0                                0.0
257                             0.0                                0.0
266                             0.0                                0.0
274                             0.0                                0.0
276                             0.0                                0.0
312                             0.0                                0.0

     attr_dietaryrestrictions_vegetarian  attr_restaurantscounterservice
3                                    0.0                             0.0
15                                   0.0                             0.0
19                                   0.0                             0.0
28                                   0.0                             0.0
31                                   0.0                             0.0
35                                   0.0                             0.0
76                                   0.0                             0.0
82                                   0.0                             0.0
130                                  0.0                             0.0
151                                  0.0                             0.0
190                                  0.0                             0.0
199                                  0.0                             0.0
205                                  0.0                             0.0
235                                  0.0                             0.0
249                                  0.0                             0.0
257                                  0.0                             0.0
266                                  0.0                             0.0
274                                  0.0                             0.0
276                                  0.0                             0.0
312                                  0.0                             0.0

[20 rows x 551 columns]

In [202]:
philly_data.shape

(6939, 551)

In [203]:
print(philly_data.filter(like='attr_').dtypes)

attr_restaurantsdelivery                object
attr_outdoorseating                     object
attr_businessacceptscreditcards         object
attr_businessparking_garage            float64
attr_businessparking_street            float64
                                        ...
attr_dietaryrestrictions_kosher        float64
attr_dietaryrestrictions_halal         float64
attr_dietaryrestrictions_soy_free      float64
attr_dietaryrestrictions_vegetarian    float64
attr_restaurantscounterservice         float64
Length: 78, dtype: object

In [204]:
philly_data['attr_restaurantsdelivery'].value_counts()

attr_restaurantsdelivery
1       3851
0       2734
None     354
Name: count, dtype: int64

In [205]:
philly_data['attr_businessparking_street'].value_counts()

attr_businessparking_street
1.0    3722
0.0    3217
Name: count, dtype: int64

In [206]:
philly_data['attr_restaurantspricerange2'].value_counts()

attr_restaurantspricerange2
2       2959
1       2613
0       1022
3.0      304
4         40
None       1
Name: count, dtype: int64

In [207]:
philly_data.filter(like='attr_').isna().sum().sort_values(ascending=False).head(30)

attr_restaurantsdelivery                0
attr_businessacceptsbitcoin             0
attr_bestnights_sunday                  0
attr_bestnights_thursday                0
attr_bestnights_wednesday               0
attr_bestnights_friday                  0
attr_bestnights_tuesday                 0
attr_bestnights_monday                  0
attr_coatcheck                          0
attr_goodfordancing                     0
attr_drivethru                          0
attr_music_karaoke                      0
attr_music_video                        0
attr_music_live                         0
attr_music_jukebox                      0
attr_music_no_music                     0
attr_music_background_music             0
attr_music_dj                           0
attr_bestnights_saturday                0
attr_corkage                            0
attr_outdoorseating                     0
attr_bestnights                         0
attr_dietaryrestrictions_vegetarian     0
attr_dietaryrestrictions_soy_free       0
attr_dietaryrestrictions_halal          0
attr_dietaryrestrictions_kosher         0
attr_dietaryrestrictions_vegan          0
attr_dietaryrestrictions_gluten_free    0
attr_dietaryrestrictions_dairy_free     0
attr_music                              0
dtype: int64

In [208]:
categorical_cols = philly_data.select_dtypes(include=['object']).columns
print(categorical_cols)

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'attributes', 'categories', 'hours', 'attr_restaurantsdelivery',
       'attr_outdoorseating', 'attr_businessacceptscreditcards',
       'attr_bikeparking', 'attr_restaurantspricerange2',
       'attr_restaurantstakeout', 'attr_wifi', 'attr_alcohol', 'attr_caters',
       'attr_restaurantsreservations', 'attr_restaurantsgoodforgroups',
       'attr_restaurantsattire', 'attr_hastv', 'attr_goodforkids',
       'attr_noiselevel', 'attr_dogsallowed', 'attr_wheelchairaccessible',
       'attr_smoking', 'attr_drivethru', 'attr_corkage', 'attr_byobcorkage',
       'attr_goodformeal', 'attr_businessparking', 'attr_ambience',
       'attr_agesallowed', 'attr_music', 'attr_bestnights'],
      dtype='object')

In [209]:
attr_categorical = philly_data.filter(like='attr_').select_dtypes(include=['object']).columns
print(attr_categorical)

Index(['attr_restaurantsdelivery', 'attr_outdoorseating',
       'attr_businessacceptscreditcards', 'attr_bikeparking',
       'attr_restaurantspricerange2', 'attr_restaurantstakeout', 'attr_wifi',
       'attr_alcohol', 'attr_caters', 'attr_restaurantsreservations',
       'attr_restaurantsgoodforgroups', 'attr_restaurantsattire', 'attr_hastv',
       'attr_goodforkids', 'attr_noiselevel', 'attr_dogsallowed',
       'attr_wheelchairaccessible', 'attr_smoking', 'attr_drivethru',
       'attr_corkage', 'attr_byobcorkage', 'attr_goodformeal',
       'attr_businessparking', 'attr_ambience', 'attr_agesallowed',
       'attr_music', 'attr_bestnights'],
      dtype='object')

In [210]:
for col in attr_categorical:
    print(f"\n{col}:")
    print(philly_data[col].value_counts())

attr_restaurantsdelivery:
attr_restaurantsdelivery
1       3851
0       2734
None     354
Name: count, dtype: int64

attr_outdoorseating:
attr_outdoorseating
0       4754
1       2015
None     170
Name: count, dtype: int64

attr_businessacceptscreditcards:
attr_businessacceptscreditcards
1       5686
0       1251
None       2
Name: count, dtype: int64

attr_bikeparking:
attr_bikeparking
1       3566
0       3369
None       4
Name: count, dtype: int64

attr_restaurantspricerange2:
attr_restaurantspricerange2
2       2959
1       2613
0       1022
3.0      304
4         40
None       1
Name: count, dtype: int64

attr_restaurantstakeout:
attr_restaurantstakeout
1       5661
0       1093
None     185
Name: count, dtype: int64

attr_wifi:
attr_wifi
0       2361
free    2300
no      2242
paid      34
None       2
Name: count, dtype: int64

attr_alcohol:
attr_alcohol
none             2970
0                2328
full_bar         1411
beer_and_wine     227
None                3
Name: count, dtype: int64

attr_caters:
attr_caters
0       4686
1       2249
None       4
Name: count, dtype: int64

attr_restaurantsreservations:
attr_restaurantsreservations
0       5160
1       1744
None      35
Name: count, dtype: int64

attr_restaurantsgoodforgroups:
attr_restaurantsgoodforgroups
1       3645
0       3290
None       4
Name: count, dtype: int64

attr_restaurantsattire:
attr_restaurantsattire
casual    4217
0         2600
dressy     112
formal       9
None         1
Name: count, dtype: int64

attr_hastv:
attr_hastv
0       3801
1       3137
None       1
Name: count, dtype: int64

attr_goodforkids:
attr_goodforkids
0       3525
1       3410
None       4
Name: count, dtype: int64

attr_noiselevel:
attr_noiselevel
0            3020
average      2675
quiet         778
loud          334
very_loud     129
None            3
Name: count, dtype: int64

attr_dogsallowed:
attr_dogsallowed
0       6677
1.0      259
None       3
Name: count, dtype: int64

attr_wheelchairaccessible:
attr_wheelchairaccessible
0       5638
1       1299
None       2
Name: count, dtype: int64

attr_smoking:
attr_smoking
0          6529
no          308
outdoor      93
yes           9
Name: count, dtype: int64

attr_drivethru:
attr_drivethru
0       6669
1.0      158
None     112
Name: count, dtype: int64

attr_corkage:
attr_corkage
0       6856
1         82
None       1
Name: count, dtype: int64

attr_byobcorkage:
attr_byobcorkage
0              6438
yes_free        254
no              228
yes_corkage      18
None              1
Name: count, dtype: int64

attr_goodformeal:
attr_goodformeal
0       6907
None      32
Name: count, dtype: int64

attr_businessparking:
attr_businessparking
0       6864
None      75
Name: count, dtype: int64

attr_ambience:
attr_ambience
0       6902
None      37
Name: count, dtype: int64

attr_agesallowed:
attr_agesallowed
0          6930
allages       5
21plus        4
Name: count, dtype: int64

attr_music:
attr_music
0       6933
None       6
Name: count, dtype: int64

attr_bestnights:
attr_bestnights
0       6938
None       1
Name: count, dtype: int64

In [211]:
binary_cols = [
    col for col in philly_data.columns 
    if col.startswith('attr_') and philly_data[col].dropna().isin([0,1]).all()
]

philly_data[binary_cols] = philly_data[binary_cols].fillna(0).astype(int)

In [212]:
philly_data['attr_restaurantspricerange2'] = (
    pd.to_numeric(philly_data['attr_restaurantspricerange2'], errors='coerce')
    .fillna(0)
    .astype(int)
)

In [213]:
philly_data['attr_wifi'] = philly_data['attr_wifi'].replace(0, 'unknown')
philly_data['attr_wifi'] = philly_data['attr_wifi'].fillna('unknown')

In [214]:
philly_data['attr_alcohol'] = philly_data['attr_alcohol'].replace(0, 'unknown')
philly_data['attr_alcohol'] = philly_data['attr_alcohol'].fillna('unknown')

In [215]:
[col for col in philly_data.columns if 'businessparking_' in col]

['attr_businessparking_garage',
 'attr_businessparking_street',
 'attr_businessparking_validated',
 'attr_businessparking_lot',
 'attr_businessparking_valet']

In [216]:
nested_prefixes = ['attr_businessparking_', 'attr_ambience_', 'attr_goodformeal_', 'attr_music_', 'attr_bestnights_']

for prefix in nested_prefixes:
    cols = [col for col in philly_data.columns if col.startswith(prefix)]
    print(f"\n{prefix}: {cols}")

attr_businessparking_: ['attr_businessparking_garage', 'attr_businessparking_street', 'attr_businessparking_validated', 'attr_businessparking_lot', 'attr_businessparking_valet']

attr_ambience_: ['attr_ambience_touristy', 'attr_ambience_hipster', 'attr_ambience_romantic', 'attr_ambience_divey', 'attr_ambience_intimate', 'attr_ambience_trendy', 'attr_ambience_upscale', 'attr_ambience_classy', 'attr_ambience_casual']

attr_goodformeal_: ['attr_goodformeal_dessert', 'attr_goodformeal_latenight', 'attr_goodformeal_lunch', 'attr_goodformeal_dinner', 'attr_goodformeal_brunch', 'attr_goodformeal_breakfast']

attr_music_: ['attr_music_dj', 'attr_music_background_music', 'attr_music_no_music', 'attr_music_jukebox', 'attr_music_live', 'attr_music_video', 'attr_music_karaoke']

attr_bestnights_: ['attr_bestnights_monday', 'attr_bestnights_tuesday', 'attr_bestnights_friday', 'attr_bestnights_wednesday', 'attr_bestnights_thursday', 'attr_bestnights_sunday', 'attr_bestnights_saturday']

In [217]:
parking_cols = [col for col in philly_data.columns if col.startswith('attr_businessparking_')]

for col in parking_cols:
    print(f"\n{col}:")
    print(philly_data[col].value_counts(dropna=False))

attr_businessparking_garage:
attr_businessparking_garage
0    6513
1     426
Name: count, dtype: int64

attr_businessparking_street:
attr_businessparking_street
1    3722
0    3217
Name: count, dtype: int64

attr_businessparking_validated:
attr_businessparking_validated
0    6818
1     121
Name: count, dtype: int64

attr_businessparking_lot:
attr_businessparking_lot
0    5899
1    1040
Name: count, dtype: int64

attr_businessparking_valet:
attr_businessparking_valet
0    6831
1     108
Name: count, dtype: int64

In [218]:
print(philly_data['attr_businessparking'].value_counts(dropna=False))

attr_businessparking
0       6864
None      75
Name: count, dtype: int64

In [219]:
categorical_cols = [
    'attr_wifi',
    'attr_alcohol',
    'attr_restaurantsattire',
    'attr_noiselevel',
    'attr_smoking',
    'attr_byobcorkage',
    'attr_agesallowed'
]

philly_data = pd.get_dummies(philly_data, columns=categorical_cols, prefix=categorical_cols)

In [220]:
# Check no object columns remain
print(philly_data.select_dtypes(include=['object']).columns)

# Check missing values
print(philly_data.isna().sum().sum())

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'attributes', 'categories', 'hours', 'attr_restaurantsdelivery',
       'attr_outdoorseating', 'attr_businessacceptscreditcards',
       'attr_bikeparking', 'attr_restaurantstakeout', 'attr_caters',
       'attr_restaurantsreservations', 'attr_restaurantsgoodforgroups',
       'attr_hastv', 'attr_goodforkids', 'attr_dogsallowed',
       'attr_wheelchairaccessible', 'attr_drivethru', 'attr_corkage',
       'attr_goodformeal', 'attr_businessparking', 'attr_ambience',
       'attr_music', 'attr_bestnights'],
      dtype='object')
1187

In [221]:
for prefix in ['attr_ambience_', 'attr_goodformeal_', 'attr_music_', 'attr_bestnights_']:
    print(prefix, [col for col in philly_data.columns if col.startswith(prefix)])

attr_ambience_ ['attr_ambience_touristy', 'attr_ambience_hipster', 'attr_ambience_romantic', 'attr_ambience_divey', 'attr_ambience_intimate', 'attr_ambience_trendy', 'attr_ambience_upscale', 'attr_ambience_classy', 'attr_ambience_casual']
attr_goodformeal_ ['attr_goodformeal_dessert', 'attr_goodformeal_latenight', 'attr_goodformeal_lunch', 'attr_goodformeal_dinner', 'attr_goodformeal_brunch', 'attr_goodformeal_breakfast']
attr_music_ ['attr_music_dj', 'attr_music_background_music', 'attr_music_no_music', 'attr_music_jukebox', 'attr_music_live', 'attr_music_video', 'attr_music_karaoke']
attr_bestnights_ ['attr_bestnights_monday', 'attr_bestnights_tuesday', 'attr_bestnights_friday', 'attr_bestnights_wednesday', 'attr_bestnights_thursday', 'attr_bestnights_sunday', 'attr_bestnights_saturday']

In [222]:
philly_data.isna().sum().sort_values(ascending=False)

hours                         1187
business_id                      0
cat_skin_care                    0
cat_shipping_centers             0
cat_shopping                     0
                              ...
cat_fruits_&_veggies             0
cat_furniture_reupholstery       0
cat_furniture_stores             0
cat_fuzhou                       0
attr_agesallowed_allages         0
Length: 577, dtype: int64

In [223]:
null_cols = philly_data.columns[philly_data.isna().any()]
print(null_cols)

Index(['hours'], dtype='object')

In [224]:
philly_data[philly_data['hours'].isna()].head(10)['time_is_open_morning']

249     0
365     0
436     0
1152    0
1344    0
1462    0
1575    0
1707    0
1821    0
1872    0
Name: time_is_open_morning, dtype: int64

In [225]:
philly_data.head(20)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attr_smoking_outdoor,attr_smoking_yes,attr_byobcorkage_0,attr_byobcorkage_None,attr_byobcorkage_no,attr_byobcorkage_yes_corkage,attr_byobcorkage_yes_free,attr_agesallowed_0,attr_agesallowed_21plus,attr_agesallowed_allages
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,False,False,True,False,False,False,False,True,False,False
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,...,False,False,True,False,False,False,False,True,False,False
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,...,False,False,True,False,False,False,False,True,False,False
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,...,False,False,True,False,False,False,False,True,False,False
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,...,False,False,True,False,False,False,False,True,False,False
35,aPNXGTDkf-4bjhyMBQxqpQ,Craft Hall,901 N Delaware Ave,Philadelphia,PA,19123,39.962582,-75.135657,3.5,65,...,False,False,True,False,False,False,False,True,False,False
76,-4dYswJy7SPcbcERvitmIg,Pathmark,3021 Grays Ferry Ave,Philadelphia,PA,19146,39.940403,-75.193297,2.5,34,...,False,False,True,False,False,False,False,True,False,False
82,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,PA,19104,39.954573,-75.194894,3.0,56,...,False,False,True,False,False,False,False,True,False,False
130,3BJxm-HnvzdwD1zjmSbmyQ,Golden Chopstick Chinese Restaurant,1800 Spring Garden St,Philadelphia,PA,19130,39.963078,-75.168027,3.0,137,...,False,False,True,False,False,False,False,True,False,False
151,WYYdQDjx-DsCanlP0DpImQ,J Sushi,243 S 10th St,Philadelphia,PA,19107,39.947033,-75.157434,4.5,72,...,False,False,True,False,False,False,False,True,False,False
190,FTFtoylMzkrzqNVSl-bkKw,Giant Food Stores,60 N 23rd St,Philadelphia,PA,19103,39.956528,-75.178014,4.0,19,...,False,False,True,False,False,False,False,True,False,False
199,O1oZpbZNDMH_gz8DhsZCdA,Wendy's,700 E. Hunting Park,Philadelphia,PA,19124,40.012141,-75.115015,1.5,15,...,False,False,True,False,False,False,False,True,False,False
205,2dlQX5sP9X6Dlm1MmNOlSw,ReAnimator Coffee,1523 E Susquehanna Ave,Philadelphia,PA,19125,39.976456,-75.127025,4.0,105,...,False,False,True,False,False,False,False,True,False,False
235,bTve2mwLk5Zc01vRKqc2KQ,Red Hook Coffee & Tea,765 S 4th St,Philadelphia,PA,19147,39.938552,-75.149636,4.5,183,...,False,False,True,False,False,False,False,True,False,False
249,bqmX882_6AxVA_uHEQ70sQ,Shanghai Station,4002 Spruce St,Philadelphia,PA,19104,39.951615,-75.203346,4.0,46,...,False,False,True,False,False,False,False,True,False,False
257,jL_NufxqXi-BpW5uXKsPwQ,CVS Pharmacy,518 Port Royal Ave,Philadelphia,PA,19128,40.061277,-75.237205,3.0,11,...,False,False,True,False,False,False,False,True,False,False
266,n8ecak12IF_jhnPNs37AZA,Baltic Bakery,2609 Edgemont St,Philadelphia,PA,19125,39.976880,-75.116169,4.5,12,...,False,False,True,False,False,False,False,True,False,False
274,_T0cPZE2ZJOTTlYYKMP64Q,Brown Sugar Bakery & Cafe,219 S 52nd St,Philadelphia,PA,19139,39.956396,-75.225378,4.5,66,...,False,False,True,False,False,False,False,True,False,False
276,VbItL6RDULtnw4YvB6EhVg,Jon's Bar & Grille,300 South St,Philadelphia,PA,19147,39.941299,-75.147745,3.0,178,...,False,False,False,False,False,False,True,True,False,False
312,V-96iACFgPmVjjKACGxd7Q,Fusion Pizza & Grill,"1900 Grant Ave, Ste M-N",Philadelphia,PA,19115,40.083996,-75.035496,2.5,6,...,False,False,True,False,False,False,False,True,False,False

In [226]:
bool_cols = []

for col in philly_data.columns:
    if philly_data[col].apply(lambda x: isinstance(x, bool)).any():
        bool_cols.append(col)

print(bool_cols)

['attr_wifi_None', 'attr_wifi_free', 'attr_wifi_no', 'attr_wifi_paid', 'attr_wifi_unknown', 'attr_alcohol_None', 'attr_alcohol_beer_and_wine', 'attr_alcohol_full_bar', 'attr_alcohol_none', 'attr_alcohol_unknown', 'attr_restaurantsattire_0', 'attr_restaurantsattire_None', 'attr_restaurantsattire_casual', 'attr_restaurantsattire_dressy', 'attr_restaurantsattire_formal', 'attr_noiselevel_0', 'attr_noiselevel_None', 'attr_noiselevel_average', 'attr_noiselevel_loud', 'attr_noiselevel_quiet', 'attr_noiselevel_very_loud', 'attr_smoking_0', 'attr_smoking_no', 'attr_smoking_outdoor', 'attr_smoking_yes', 'attr_byobcorkage_0', 'attr_byobcorkage_None', 'attr_byobcorkage_no', 'attr_byobcorkage_yes_corkage', 'attr_byobcorkage_yes_free', 'attr_agesallowed_0', 'attr_agesallowed_21plus', 'attr_agesallowed_allages']

In [227]:
onehot_bool_cols = [
    'attr_wifi_None', 'attr_wifi_free', 'attr_wifi_no', 'attr_wifi_paid', 'attr_wifi_unknown',
    'attr_alcohol_None', 'attr_alcohol_beer_and_wine', 'attr_alcohol_full_bar',
    'attr_alcohol_none', 'attr_alcohol_unknown',
    'attr_restaurantsattire_0', 'attr_restaurantsattire_None', 'attr_restaurantsattire_casual',
    'attr_restaurantsattire_dressy', 'attr_restaurantsattire_formal',
    'attr_noiselevel_0', 'attr_noiselevel_None', 'attr_noiselevel_average',
    'attr_noiselevel_loud', 'attr_noiselevel_quiet', 'attr_noiselevel_very_loud',
    'attr_smoking_0', 'attr_smoking_no', 'attr_smoking_outdoor', 'attr_smoking_yes',
    'attr_byobcorkage_0', 'attr_byobcorkage_None', 'attr_byobcorkage_no',
    'attr_byobcorkage_yes_corkage', 'attr_byobcorkage_yes_free',
    'attr_agesallowed_0', 'attr_agesallowed_21plus', 'attr_agesallowed_allages'
]

philly_data[onehot_bool_cols] = philly_data[onehot_bool_cols].astype(int)

In [228]:
print(philly_data.select_dtypes(include=['bool']).columns)

Index([], dtype='object')

In [229]:
print(philly_data.select_dtypes(include=['object']).columns)

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'attributes', 'categories', 'hours', 'attr_restaurantsdelivery',
       'attr_outdoorseating', 'attr_businessacceptscreditcards',
       'attr_bikeparking', 'attr_restaurantstakeout', 'attr_caters',
       'attr_restaurantsreservations', 'attr_restaurantsgoodforgroups',
       'attr_hastv', 'attr_goodforkids', 'attr_dogsallowed',
       'attr_wheelchairaccessible', 'attr_drivethru', 'attr_corkage',
       'attr_goodformeal', 'attr_businessparking', 'attr_ambience',
       'attr_music', 'attr_bestnights'],
      dtype='object')

In [230]:
philly_data.to_csv('output_philly.csv', index=False)

In [231]:
for col in philly_data.columns:
    if philly_data[col].astype(str).str.contains('None').any():
        print(col)

attributes
attr_restaurantsdelivery
attr_outdoorseating
attr_businessacceptscreditcards
attr_bikeparking
attr_restaurantstakeout
attr_caters
attr_restaurantsreservations
attr_restaurantsgoodforgroups
attr_hastv
attr_goodforkids
attr_dogsallowed
attr_wheelchairaccessible
attr_drivethru
attr_corkage
attr_goodformeal
attr_businessparking
attr_ambience
attr_music
attr_bestnights

In [232]:
binary_attr_cols = [
    'attr_restaurantsdelivery',
    'attr_outdoorseating',
    'attr_businessacceptscreditcards',
    'attr_bikeparking',
    'attr_restaurantstakeout',
    'attr_caters',
    'attr_restaurantsreservations',
    'attr_restaurantsgoodforgroups',
    'attr_hastv',
    'attr_goodforkids',
    'attr_dogsallowed',
    'attr_wheelchairaccessible',
    'attr_drivethru',
    'attr_corkage'
]

for col in binary_attr_cols:
    if col in philly_data.columns:
        philly_data[col] = (
            philly_data[col]
            .replace('None', 0)
            .fillna(0)
            .astype(int)
        )

/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)
/var/folders/z7/8sfcftc51bz6vrphft4gwf300000gn/T/ipykernel_54922/1554355666.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('None', 0)

In [233]:
philly_data.head(20)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attr_smoking_outdoor,attr_smoking_yes,attr_byobcorkage_0,attr_byobcorkage_None,attr_byobcorkage_no,attr_byobcorkage_yes_corkage,attr_byobcorkage_yes_free,attr_agesallowed_0,attr_agesallowed_21plus,attr_agesallowed_allages
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,0,0,1,0,0,0,0,1,0,0
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,...,0,0,1,0,0,0,0,1,0,0
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,...,0,0,1,0,0,0,0,1,0,0
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,...,0,0,1,0,0,0,0,1,0,0
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,...,0,0,1,0,0,0,0,1,0,0
35,aPNXGTDkf-4bjhyMBQxqpQ,Craft Hall,901 N Delaware Ave,Philadelphia,PA,19123,39.962582,-75.135657,3.5,65,...,0,0,1,0,0,0,0,1,0,0
76,-4dYswJy7SPcbcERvitmIg,Pathmark,3021 Grays Ferry Ave,Philadelphia,PA,19146,39.940403,-75.193297,2.5,34,...,0,0,1,0,0,0,0,1,0,0
82,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,PA,19104,39.954573,-75.194894,3.0,56,...,0,0,1,0,0,0,0,1,0,0
130,3BJxm-HnvzdwD1zjmSbmyQ,Golden Chopstick Chinese Restaurant,1800 Spring Garden St,Philadelphia,PA,19130,39.963078,-75.168027,3.0,137,...,0,0,1,0,0,0,0,1,0,0
151,WYYdQDjx-DsCanlP0DpImQ,J Sushi,243 S 10th St,Philadelphia,PA,19107,39.947033,-75.157434,4.5,72,...,0,0,1,0,0,0,0,1,0,0
190,FTFtoylMzkrzqNVSl-bkKw,Giant Food Stores,60 N 23rd St,Philadelphia,PA,19103,39.956528,-75.178014,4.0,19,...,0,0,1,0,0,0,0,1,0,0
199,O1oZpbZNDMH_gz8DhsZCdA,Wendy's,700 E. Hunting Park,Philadelphia,PA,19124,40.012141,-75.115015,1.5,15,...,0,0,1,0,0,0,0,1,0,0
205,2dlQX5sP9X6Dlm1MmNOlSw,ReAnimator Coffee,1523 E Susquehanna Ave,Philadelphia,PA,19125,39.976456,-75.127025,4.0,105,...,0,0,1,0,0,0,0,1,0,0
235,bTve2mwLk5Zc01vRKqc2KQ,Red Hook Coffee & Tea,765 S 4th St,Philadelphia,PA,19147,39.938552,-75.149636,4.5,183,...,0,0,1,0,0,0,0,1,0,0
249,bqmX882_6AxVA_uHEQ70sQ,Shanghai Station,4002 Spruce St,Philadelphia,PA,19104,39.951615,-75.203346,4.0,46,...,0,0,1,0,0,0,0,1,0,0
257,jL_NufxqXi-BpW5uXKsPwQ,CVS Pharmacy,518 Port Royal Ave,Philadelphia,PA,19128,40.061277,-75.237205,3.0,11,...,0,0,1,0,0,0,0,1,0,0
266,n8ecak12IF_jhnPNs37AZA,Baltic Bakery,2609 Edgemont St,Philadelphia,PA,19125,39.976880,-75.116169,4.5,12,...,0,0,1,0,0,0,0,1,0,0
274,_T0cPZE2ZJOTTlYYKMP64Q,Brown Sugar Bakery & Cafe,219 S 52nd St,Philadelphia,PA,19139,39.956396,-75.225378,4.5,66,...,0,0,1,0,0,0,0,1,0,0
276,VbItL6RDULtnw4YvB6EhVg,Jon's Bar & Grille,300 South St,Philadelphia,PA,19147,39.941299,-75.147745,3.0,178,...,0,0,0,0,0,0,1,1,0,0
312,V-96iACFgPmVjjKACGxd7Q,Fusion Pizza & Grill,"1900 Grant Ave, Ste M-N",Philadelphia,PA,19115,40.083996,-75.035496,2.5,6,...,0,0,1,0,0,0,0,1,0,0

In [234]:
philly_data.to_csv('new_output_philly.csv', index=False)

In [235]:
philly_data.head(20)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attr_smoking_outdoor,attr_smoking_yes,attr_byobcorkage_0,attr_byobcorkage_None,attr_byobcorkage_no,attr_byobcorkage_yes_corkage,attr_byobcorkage_yes_free,attr_agesallowed_0,attr_agesallowed_21plus,attr_agesallowed_allages
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,0,0,1,0,0,0,0,1,0,0
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,...,0,0,1,0,0,0,0,1,0,0
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,...,0,0,1,0,0,0,0,1,0,0
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,...,0,0,1,0,0,0,0,1,0,0
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,...,0,0,1,0,0,0,0,1,0,0
35,aPNXGTDkf-4bjhyMBQxqpQ,Craft Hall,901 N Delaware Ave,Philadelphia,PA,19123,39.962582,-75.135657,3.5,65,...,0,0,1,0,0,0,0,1,0,0
76,-4dYswJy7SPcbcERvitmIg,Pathmark,3021 Grays Ferry Ave,Philadelphia,PA,19146,39.940403,-75.193297,2.5,34,...,0,0,1,0,0,0,0,1,0,0
82,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,PA,19104,39.954573,-75.194894,3.0,56,...,0,0,1,0,0,0,0,1,0,0
130,3BJxm-HnvzdwD1zjmSbmyQ,Golden Chopstick Chinese Restaurant,1800 Spring Garden St,Philadelphia,PA,19130,39.963078,-75.168027,3.0,137,...,0,0,1,0,0,0,0,1,0,0
151,WYYdQDjx-DsCanlP0DpImQ,J Sushi,243 S 10th St,Philadelphia,PA,19107,39.947033,-75.157434,4.5,72,...,0,0,1,0,0,0,0,1,0,0
190,FTFtoylMzkrzqNVSl-bkKw,Giant Food Stores,60 N 23rd St,Philadelphia,PA,19103,39.956528,-75.178014,4.0,19,...,0,0,1,0,0,0,0,1,0,0
199,O1oZpbZNDMH_gz8DhsZCdA,Wendy's,700 E. Hunting Park,Philadelphia,PA,19124,40.012141,-75.115015,1.5,15,...,0,0,1,0,0,0,0,1,0,0
205,2dlQX5sP9X6Dlm1MmNOlSw,ReAnimator Coffee,1523 E Susquehanna Ave,Philadelphia,PA,19125,39.976456,-75.127025,4.0,105,...,0,0,1,0,0,0,0,1,0,0
235,bTve2mwLk5Zc01vRKqc2KQ,Red Hook Coffee & Tea,765 S 4th St,Philadelphia,PA,19147,39.938552,-75.149636,4.5,183,...,0,0,1,0,0,0,0,1,0,0
249,bqmX882_6AxVA_uHEQ70sQ,Shanghai Station,4002 Spruce St,Philadelphia,PA,19104,39.951615,-75.203346,4.0,46,...,0,0,1,0,0,0,0,1,0,0
257,jL_NufxqXi-BpW5uXKsPwQ,CVS Pharmacy,518 Port Royal Ave,Philadelphia,PA,19128,40.061277,-75.237205,3.0,11,...,0,0,1,0,0,0,0,1,0,0
266,n8ecak12IF_jhnPNs37AZA,Baltic Bakery,2609 Edgemont St,Philadelphia,PA,19125,39.976880,-75.116169,4.5,12,...,0,0,1,0,0,0,0,1,0,0
274,_T0cPZE2ZJOTTlYYKMP64Q,Brown Sugar Bakery & Cafe,219 S 52nd St,Philadelphia,PA,19139,39.956396,-75.225378,4.5,66,...,0,0,1,0,0,0,0,1,0,0
276,VbItL6RDULtnw4YvB6EhVg,Jon's Bar & Grille,300 South St,Philadelphia,PA,19147,39.941299,-75.147745,3.0,178,...,0,0,0,0,0,0,1,1,0,0
312,V-96iACFgPmVjjKACGxd7Q,Fusion Pizza & Grill,"1900 Grant Ave, Ste M-N",Philadelphia,PA,19115,40.083996,-75.035496,2.5,6,...,0,0,1,0,0,0,0,1,0,0

In [236]:
cols_with_none = [col for col in philly_data.columns 
                  if (philly_data[col] == 'None').any()]

print(cols_with_none)

['attr_goodformeal', 'attr_businessparking', 'attr_ambience', 'attr_music', 'attr_bestnights']

In [238]:
for col in cols_with_none:
    print(f"\nColumn: {col}")
    print(philly_data[col].value_counts(dropna=False))

Column: attr_goodformeal
attr_goodformeal
0       6907
None      32
Name: count, dtype: int64

Column: attr_businessparking
attr_businessparking
0       6864
None      75
Name: count, dtype: int64

Column: attr_ambience
attr_ambience
0       6902
None      37
Name: count, dtype: int64

Column: attr_music
attr_music
0       6933
None       6
Name: count, dtype: int64

Column: attr_bestnights
attr_bestnights
0       6938
None       1
Name: count, dtype: int64

In [239]:
philly_data = philly_data.drop(columns=cols_with_none)

In [240]:
philly_data.head(20)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attr_smoking_outdoor,attr_smoking_yes,attr_byobcorkage_0,attr_byobcorkage_None,attr_byobcorkage_no,attr_byobcorkage_yes_corkage,attr_byobcorkage_yes_free,attr_agesallowed_0,attr_agesallowed_21plus,attr_agesallowed_allages
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,0,0,1,0,0,0,0,1,0,0
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,...,0,0,1,0,0,0,0,1,0,0
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,...,0,0,1,0,0,0,0,1,0,0
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,...,0,0,1,0,0,0,0,1,0,0
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,...,0,0,1,0,0,0,0,1,0,0
35,aPNXGTDkf-4bjhyMBQxqpQ,Craft Hall,901 N Delaware Ave,Philadelphia,PA,19123,39.962582,-75.135657,3.5,65,...,0,0,1,0,0,0,0,1,0,0
76,-4dYswJy7SPcbcERvitmIg,Pathmark,3021 Grays Ferry Ave,Philadelphia,PA,19146,39.940403,-75.193297,2.5,34,...,0,0,1,0,0,0,0,1,0,0
82,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,PA,19104,39.954573,-75.194894,3.0,56,...,0,0,1,0,0,0,0,1,0,0
130,3BJxm-HnvzdwD1zjmSbmyQ,Golden Chopstick Chinese Restaurant,1800 Spring Garden St,Philadelphia,PA,19130,39.963078,-75.168027,3.0,137,...,0,0,1,0,0,0,0,1,0,0
151,WYYdQDjx-DsCanlP0DpImQ,J Sushi,243 S 10th St,Philadelphia,PA,19107,39.947033,-75.157434,4.5,72,...,0,0,1,0,0,0,0,1,0,0
190,FTFtoylMzkrzqNVSl-bkKw,Giant Food Stores,60 N 23rd St,Philadelphia,PA,19103,39.956528,-75.178014,4.0,19,...,0,0,1,0,0,0,0,1,0,0
199,O1oZpbZNDMH_gz8DhsZCdA,Wendy's,700 E. Hunting Park,Philadelphia,PA,19124,40.012141,-75.115015,1.5,15,...,0,0,1,0,0,0,0,1,0,0
205,2dlQX5sP9X6Dlm1MmNOlSw,ReAnimator Coffee,1523 E Susquehanna Ave,Philadelphia,PA,19125,39.976456,-75.127025,4.0,105,...,0,0,1,0,0,0,0,1,0,0
235,bTve2mwLk5Zc01vRKqc2KQ,Red Hook Coffee & Tea,765 S 4th St,Philadelphia,PA,19147,39.938552,-75.149636,4.5,183,...,0,0,1,0,0,0,0,1,0,0
249,bqmX882_6AxVA_uHEQ70sQ,Shanghai Station,4002 Spruce St,Philadelphia,PA,19104,39.951615,-75.203346,4.0,46,...,0,0,1,0,0,0,0,1,0,0
257,jL_NufxqXi-BpW5uXKsPwQ,CVS Pharmacy,518 Port Royal Ave,Philadelphia,PA,19128,40.061277,-75.237205,3.0,11,...,0,0,1,0,0,0,0,1,0,0
266,n8ecak12IF_jhnPNs37AZA,Baltic Bakery,2609 Edgemont St,Philadelphia,PA,19125,39.976880,-75.116169,4.5,12,...,0,0,1,0,0,0,0,1,0,0
274,_T0cPZE2ZJOTTlYYKMP64Q,Brown Sugar Bakery & Cafe,219 S 52nd St,Philadelphia,PA,19139,39.956396,-75.225378,4.5,66,...,0,0,1,0,0,0,0,1,0,0
276,VbItL6RDULtnw4YvB6EhVg,Jon's Bar & Grille,300 South St,Philadelphia,PA,19147,39.941299,-75.147745,3.0,178,...,0,0,0,0,0,0,1,1,0,0
312,V-96iACFgPmVjjKACGxd7Q,Fusion Pizza & Grill,"1900 Grant Ave, Ste M-N",Philadelphia,PA,19115,40.083996,-75.035496,2.5,6,...,0,0,1,0,0,0,0,1,0,0

In [241]:
philly_data.to_csv('updated_philly_data.csv', index=False)